### ISSUE TITLE
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead

### ISSUE THREAD

**Issue by michaelbull** [aurelia/metadata#56] opened 2018-03-21 11:16 UTC
**I'm submitting a bug report**

* **Library Version:**
1.0.3

**Please tell us about your environment:**
* **Operating System:**
Linux F27

* **Node Version:**
8.9.4

* **NPM Version:**
5.6.0

* **JSPM OR Webpack AND Version**
webpack 4

* **Browser:**
Chrome Version 65.0.3325.146 (Official Build) (64-bit)

* **Language:**
TypeScript 2.7.2

**Current behavior:**

I just started using viewports in a few of my routing behaviours. The Chrome devtools console is giving me this warning:

```
aurelia-metadata.js?c04d:64 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
(anonymous) @ aurelia-metadata.js?c04d:64
(anonymous) @ aurelia-loader-webpack.js?b873:144
WebpackLoader.__WEBPACK_IMPORTED_MODULE_2_aurelia_pal__.PLATFORM.eachModule @ aurelia-loader-webpack.js?b873:141
get @ aurelia-metadata.js?c04d:61
getViewStrategy @ aurelia-templating.js?f83c:690
process @ router-view.js?e967:113
_loop @ aurelia-router.js?ec12:291
_commitChanges @ aurelia-router.js?ec12:305
(anonymous) @ aurelia-router.js?ec12:293
Promise.then (async)
_loop @ aurelia-router.js?ec12:291
_commitChanges @ aurelia-router.js?ec12:305
(anonymous) @ aurelia-router.js?ec12:293
Promise.then (async)
_loop @ aurelia-router.js?ec12:291
_commitChanges @ aurelia-router.js?ec12:305
run @ aurelia-router.js?ec12:143
next @ aurelia-router.js?ec12:112
iterate @ aurelia-router.js?ec12:1302
inspect @ aurelia-router.js?ec12:1279
(anonymous) @ aurelia-router.js?ec12:1295
```

It is specifically complaining about [this line](https://github.com/aurelia/metadata/blob/1f4c3e4ea4540b3842ed0e9d987e20a42f02eff4/dist/commonjs/aurelia-metadata.js#L76)

![Console](https://i.imgur.com/BZ6GfwO.png)

**Expected/desired behavior:**

* **What is the expected behavior?**

The library should be updated to not use the deprecated functionality.

* **What is the motivation / use case for changing the behavior?**

Remove console deprecation warnings

**Comment by Alexander-Taran** [comment] 2018-03-21 12:14
Would you like to provide a pull request for this one @michaelbull ?
something like `let storageInfo = navigator.webkitTemporaryStorage || window.webkitStorageInfo`

**Comment by avrahamcool** [comment] 2018-05-21 08:52
it's hard to track down.
at runtime, we get the warning from the `metadata` code, but the package doesn't actually use `window.webkitStorageInfo`.
it looks like that some other code uses `window.webkitStorageInfo` and load it into the `metadata`'s `origin` Map.

I've tried to find the source of the problem (it must be loaded into one of my bundles, right?) but didn't succeed.

**Comment by avrahamcool** [comment] 2018-05-21 09:17
when `./node_modules/webpack/buildin/global.js` is loaded, the value is `window`.
iterating over the `window` properties causes this issue (because the deprecated property is still there).

![image](https://user-images.githubusercontent.com/5445320/40299237-4d92eeec-5cee-11e8-8456-b2ee2c2674a7.png)

this can be fixed like shown [here](https://stackoverflow.com/questions/36060329/window-webkitstorageinfo-is-deprecated-warning-while-iterating-window-object).

but it's actually pointless, because when it will be actually removed - then it will not show up in the `for.. of` and problem solved.

**Comment by EisenbergEffect** [comment] 2018-06-12 06:28
Closing this since there's a workaround. Also, we'll merge a PR that prevents exceptions during enumeration, shortly.

**Closed by EisenbergEffect** 2018-06-12 06:28 UTC

**Comment by smajl** [comment] 2018-10-29 10:40
@EisenbergEffect Hi, any updates on the official patch? Was that aforementioned PR even created?

**Comment by EisenbergEffect** [comment] 2018-10-29 16:32
@smajl The patch was merged, yes.

**Comment by LilSebastian5000** [comment] 2019-01-07 19:01
So this is still being worked on and we should ignore the warning?

**Comment by abowen** [comment] 2019-12-12 06:07
I've installed version 1.0.6 and still getting this warning.

**Comment by GustavRoder** [comment] 2020-04-30 07:56
Yup, the problem is still here with version 1.0.6 :)

**Comment by bigopon** [comment] 2020-05-09 05:15
Let me have a go at fixing this annoying warning then. Thanks for nudging

**Comment by josundt** [comment] 2020-10-11 00:34
@bigopon I added PR #65 with a quick fix to this warning that has been a console distraction for some time now.
